name: Build & Test CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build packages
        run: yarn build
      - name: Automated tests
        run: yarn test
      - name: Visual regression tests
        uses: chromaui/action@v1
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: yarn test:chromatic
